# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resources.libraries.dictable.dictable


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0004_auto_20160227_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.TextBlock')),
            ],
            bases=(models.Model, resources.libraries.dictable.dictable.Dictable),
        ),
        migrations.CreateModel(
            name='GameAttributeModifier',
            fields=[
                ('attributemodifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.AttributeModifier')),
                ('expires', models.BooleanField(default=False)),
                ('duration', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Game')),
            ],
            bases=('resources.attributemodifier',),
        ),
        migrations.CreateModel(
            name='GameCharacter',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Character')),
                ('x_position', models.IntegerField(default=0)),
                ('y_position', models.IntegerField(default=0)),
                ('z_position', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Game')),
            ],
            bases=('resources.character',),
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, resources.libraries.dictable.dictable.Dictable),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'Player', max_length=255)),
                ('mastered_games', models.ManyToManyField(to='resources.Game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, resources.libraries.dictable.dictable.Dictable),
        ),
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('map_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Map')),
            ],
            bases=('resources.map',),
        ),
        migrations.AddField(
            model_name='map',
            name='adventures',
            field=models.ManyToManyField(to='resources.Adventure'),
        ),
        migrations.AddField(
            model_name='map',
            name='campaign_settings',
            field=models.ManyToManyField(to='resources.CampaignSetting'),
        ),
        migrations.AddField(
            model_name='gameattributemodifier',
            name='targets',
            field=models.ManyToManyField(to='resources.GameCharacter'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_masters',
            field=models.ManyToManyField(to='resources.Player'),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Game'),
        ),
    ]
